### ISSUE TITLE
andi added to homebrew-science

### ISSUE THREAD

**Issue by tseemann** [EvolBioInf/andi#4]
FYI - I managed to get it packaged:

https://github.com/Homebrew/homebrew-science/pull/2372

**Comment by kloetzl** [comment]
Cool, thanks.

The error mentioned [here](https://github.com/Homebrew/homebrew-science/pull/2372) has been fixed in the last [commit](https://github.com/EvolBioInf/andi/commit/6667295c1141121a8e0014d437711df443d42ae4). I will bundle that into a new version, in a few days time. Can you make homebrew automatically load the latest stable release?

**Comment by kloetzl** [comment]
The issue should be fixed in [v0.9.2](https://github.com/EvolBioInf/andi/releases/tag/v0.9.2).

**Comment by tseemann** [comment]
@kloetzl No we can't do automatic updates but I've updated the formula and it hopefully should pass on OS X soon! Thanks for helping.

**Comment by kloetzl** [comment]
Thanks for distributing andi!
